version: '3'
services:
  api:
    build:
      context: .
    image: alexandreesl/gatling_lab
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-server -Xms512m -Xmx512m
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: gatling
      POSTGRES_PASSWORD: gatling
      POSTGRES_USER: gatling
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 30
  flyway:
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:postgresql://postgres/gatling -user=gatling -password=gatling -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
  gatling:
    image: denvazh/gatling
    volumes:
      - ./src/gatling/conf:/opt/gatling/conf
      - ./src/gatling/simulations:/opt/gatling/user-files/simulations
      - ./src/gatling/results:/opt/gatling/results
    depends_on:
      - api
